export interface GinecoObstetros
{
    menarca: string,
        ritmo: string,
        cantidad: string,
        toallas: string,
        dolor: string,
        tratamiento: string,
        fum: string,
        ivsa: string,
        parejas: string,
        mpf: string,
        gestas: string,
        cesareas: string,
        partos: string,
        abortos: string,
        ectopicos: string,
        citologiaVertical: string,
        docma: string,
        autoexploracion: string,
        usg: string,
        mastografia: string,
        menopausia: string,
        antecedentesInfertilidad: string,
        g1: {
            anio: number,
            edad: number,
            duracion: string,
            sexo: string,
            peso: string,
            vivoSano: boolean,
            resol: string,
            comp: string,
            lactancia: string
        },
        g2: {
            anio: number,
            edad: number,
            duracion: string,
            sexo: string,
            peso: string,
            vivoSano: boolean,
            resol: string,
            comp: string,
            lactancia: string
        },
        g3: {
            anio: number,
            edad: number,
            duracion: string,
            sexo: string,
            peso: string,
            vivoSano: boolean,
            resol: string,
            comp: string,
            lactancia: string
        },
        g4: {
            anio: number,
            edad: number,
            duracion: string,
            sexo: string,
            peso: string,
            vivoSano: boolean,
            resol: string,
            comp: string,
            lactancia: string
        }
}